### ISSUE TITLE
sentry-sdk в зависимостях

### ISSUE THREAD

**Issue by Dave-YP** [andrei-samofalov/e-shop-django#2]
sentry-sdk не хватает в зависимостях - ModuleNotFoundError: No module named 'sentry_sdk' + pip install clearcache-python +pip install django-debug-toolbar. Миграции не проходят -   File "C:\Users\Gagarin\YP\e-shop-django-master\shop\catalog\admin.py", line 30, in <module>
    class SubcategoriesInline(admin.TabularInline):
  File "C:\Users\Gagarin\YP\e-shop-django-master\shop\catalog\admin.py", line 34, in SubcategoriesInline
    verbose_name = _('parent category')
NameError: name '_' is not defined

**Comment by andrei-samofalov** [comment]
привет!
спасибо за сообщение.
демо-версия не предполагает установки и использования инструментов разработчика. 
флаг debug исправлен на False
